### ISSUE TITLE
To add

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/awesome-code-ai#13]
Links I will make PRs for eventually

* https://huggingface.co/cerebras/Cerebras-GPT-13B
  * https://www.cerebras.net/blog/cerebras-gpt-a-family-of-open-compute-efficient-large-language-models/
* https://github.com/TaxyAI/browser-extension

**Comment by keynmol** [comment]
And perhaps... Cody? :D

**Comment by SuperAuguste** [comment]
Hi @keynmol, thanks for commenting on this issue and welcome to the Sourcegraph community! We'd be happy if you opened a PR adding Cody to this list. :)
